# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yarka/development/MSHP/c_cpp/Decipherer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yarka/development/MSHP/c_cpp/Decipherer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yarka/development/MSHP/c_cpp/Decipherer/CMakeFiles /home/yarka/development/MSHP/c_cpp/Decipherer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yarka/development/MSHP/c_cpp/Decipherer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hamming

# Build rule for target.
hamming: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hamming
.PHONY : hamming

# fast build rule for target.
hamming/fast:
	$(MAKE) -f CMakeFiles/hamming.dir/build.make CMakeFiles/hamming.dir/build
.PHONY : hamming/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

Decipherer.o: Decipherer.cpp.o

.PHONY : Decipherer.o

# target to build an object file
Decipherer.cpp.o:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Decipherer.cpp.o
.PHONY : Decipherer.cpp.o

Decipherer.i: Decipherer.cpp.i

.PHONY : Decipherer.i

# target to preprocess a source file
Decipherer.cpp.i:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Decipherer.cpp.i
.PHONY : Decipherer.cpp.i

Decipherer.s: Decipherer.cpp.s

.PHONY : Decipherer.s

# target to generate assembly for a file
Decipherer.cpp.s:
	$(MAKE) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/Decipherer.cpp.s
.PHONY : Decipherer.cpp.s

Hamming.o: Hamming.cpp.o

.PHONY : Hamming.o

# target to build an object file
Hamming.cpp.o:
	$(MAKE) -f CMakeFiles/hamming.dir/build.make CMakeFiles/hamming.dir/Hamming.cpp.o
.PHONY : Hamming.cpp.o

Hamming.i: Hamming.cpp.i

.PHONY : Hamming.i

# target to preprocess a source file
Hamming.cpp.i:
	$(MAKE) -f CMakeFiles/hamming.dir/build.make CMakeFiles/hamming.dir/Hamming.cpp.i
.PHONY : Hamming.cpp.i

Hamming.s: Hamming.cpp.s

.PHONY : Hamming.s

# target to generate assembly for a file
Hamming.cpp.s:
	$(MAKE) -f CMakeFiles/hamming.dir/build.make CMakeFiles/hamming.dir/Hamming.cpp.s
.PHONY : Hamming.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hamming"
	@echo "... run"
	@echo "... Decipherer.o"
	@echo "... Decipherer.i"
	@echo "... Decipherer.s"
	@echo "... Hamming.o"
	@echo "... Hamming.i"
	@echo "... Hamming.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

